#fork_me_ribbon_url: https://github.com/NordicESMhub/noresmdiagnostics
baseurl: "/noresmdiagnostics"
title: "NorESM output and post-processing"

author:
  name: Yanchun He
  link: https://www.nersc.no/staff/yanchun-he

source: .
destination: ./_site
layouts_dir: ./jekyll-common/layouts
includes_dir: ./jekyll-common/includes

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

include: ['jekyll-common/pages']
exclude: ['LICENSE']

collections:
  episodes:
    output: true
    permalink: /:name/
